### ISSUE TITLE
Manually trigger update

### ISSUE THREAD

**Issue by ultimate-tester** [chandlerprall/DatabindExtension#1]
Hi,

For a high performance application I'm currently writing I would like to use this extension to dynamically update data in the template. I can't however, have the system check every frame to see if there are changes to the bound elements. 

To improve performance, I would like to see an option to switch from auto-update to manually update, and add a method to trigger the update.

What do you think? If you found I'll provide a Pull request for this :)

**Comment by chandlerprall** [comment]
A PR would be great, thanks!

**Comment by ultimate-tester** [comment]
See #3

**Comment by chandlerprall** [comment]
merged #3
