### ISSUE TITLE
Circular structure with createContext function create infinite loop

### ISSUE THREAD

**Issue by Speuta** [chandlerprall/DatabindExtension#13]
You can test with this simple script:

`var a = {};
var b = {a: a};
a.b = b;
databindExtension.createContext(a);`

Maybe add a isProxy attribute.

**Comment by ultimate-tester** [comment]
To fix this one properly, what would you like to see instead? An error in console (serious question, I'm not sure what is more user friendly).

**Comment by ultimate-tester** [comment]
As part of 3.0.0 this is now also done. Previously proxified objects will no longer be proxified again (causing an infinite loop). Thanks for waiting 3+ years ;)
