### ISSUE TITLE
Specify bind element ID prefix

### ISSUE THREAD

**Issue by ultimate-tester** [chandlerprall/DatabindExtension#2]
Hi,

Currently the bind element has a fixed prefix "boundelement-". I would like to create an option to change this prefix.

If you'd like I'll provide a Pull request for this?

**Comment by chandlerprall** [comment]
A PR would be great, thanks!

**Comment by ultimate-tester** [comment]
See #3

**Comment by chandlerprall** [comment]
merged #3
