### ISSUE TITLE
Passing multiple parameters that can trigger a re-render

### ISSUE THREAD

**Issue by halfmoonui** [chandlerprall/DatabindExtension#28]
Take this code from the README:

```
{% bind "items" %}
    <ul>
    {% for item in items %}
        <li>{{item}}</li>
    {% endfor %}
    </ul>
{% endbind %}
```

Is there a way to pass in multiple parameters (instead of just one). A change in any one one would trigger a re-render. For example, something like this:

```
{% bind "items" "myCondition" %}
    ...
{% endbind %}
```

**Comment by ultimate-tester** [comment]
This functionality is not provided.

You could make multiple wraps around with different bind variables.

Though, if you have this use case you are probably not wrapping specific/deep enough elements. Could you provide me with a fragment of the real use case that shows why binding to multiple variables would be needed?

**Comment by halfmoonui** [comment]
@ultimate-tester Thanks for the response. And that's a very fair point. My use case is something along these lines:

I can have multiple attributes in my `data` (created via `databindExtension.createContext`), but I would not want all of them to be binded to the re-render function because that's not performant. Ideally, I would like to choose which ones. Of course, I can have something like this:

```
{
  binded: {...},
  ...
}
```

and just bind the `binded` key of the data, but actually using the binded variables would become less cleaner. For example, instead of doing `{{ name }}`, I would have to write `{{ binded.name }}` on the template. Hope that was clear enough. In general, I think the DX would be really nice with this approach, very clean variable names and we would get to pick and choose which ones to use for re-rendering with only one bind tag.

**Comment by ultimate-tester** [comment]
I'm sorry, I don't understand it yet. 

The idea is that you give the property name/key within your context to the bind tags. When only that specific property changes, the re-render is triggered. It's not monitoring the entire context for change and re rendering. It seems that this is exactly what you want.

Am I misunderstanding?

**Comment by halfmoonui** [comment]
@ultimate-tester Hmm I think so, sorry it's a bit hard for me to explain. Maybe I can create fork and write it myself. Could you point to the place where the binding parameter is actually being used to make sure only changes to that part of the object triggers a re-render?

**Comment by ultimate-tester** [comment]
A good place to start would be the updatebindings method within the main databindextension js file.

**Comment by halfmoonui** [comment]
@ultimate-tester Thank you so much!

**Comment by halfmoonui** [comment]
Are there any performance issues with nesting multiple `bind` tags, each with its own "binded" parameter? Let's say 10-20 or something in that range.

**Comment by ultimate-tester** [comment]
There shouldn't be, but consider looking at your HTML structure and wrapping the most specific child element each with new bind tags. It's unlikely that you have multiple dynamic properties in your context that need to be printed next to each other within the same tag. If you could give me a fragment of your html structure I could probably show a more specific example that would work for you.

**Comment by halfmoonui** [comment]
Got it, that makes sense. So in terms of my HTML fragment, basically it's for something user-facing, so the HTML would vary from one user to another. Instead of users having to declare `{% bind  "whatever" %}` tags all over the DOM, I figured it would be a lot easier if the system just declares it once at the top and specifies which data attributes should force a re-render.

Not important in this context, but the user would somehow indicate which attributes would force re-render in some other way which I would pass to the system.

**Comment by ultimate-tester** [comment]
Ah gotcha that makes sense. So the HTML is provided by the user and you do not want to require the user to place bind tags wherever necessary.

A while ago I tried to achieve the functionality of not needing bind tags anymore at all, simply look at the variables that are being rendered and keep monitoring those. I might just pick this up again.. let me see if I have some time this weekend.

For right now, indeed wrapping the full custom user input HTML fragment would be best without performance impact.

**Comment by halfmoonui** [comment]
Yep that's exactly it. I'll be monitoring the progress on this. This is a great library that really does something super cool in a very simple and elegant way. Thanks a lot!

**Comment by ultimate-tester** [comment]
This is now done! It took a bit more than just a day in the weekend but luckily it took more effort in the thinking process rather than the coding itself which helped the module to stay quite small (~80kb). It was necessary to completely overhaul the approach which also means the usage has changed.

You'll find the updated way of usage in the README file. In case of any questions or bug findings just open a new ticket :)
