### ISSUE TITLE
Publish this extension

### ISSUE THREAD

**Issue by ultimate-tester** [chandlerprall/DatabindExtension#5]
I wondered before why this extension is not that "popular". I mean it's used, but I think it could be made more available if you understand what I mean. I realized that this package is not published to, for example, npm.

Just a suggestion: Publish this package to npm perhaps. This extension is absolutely relevant for a lot of people but I have the feeling they don't know about this extension. Just something for you to think about perhaps 👍

**Comment by chandlerprall** [comment]
To be honest, I created this while evaluating nunjucks against some other libraries; eventually our team chose React and I never used this in any real application. Feel free to fork & publish!

**Comment by ultimate-tester** [comment]
Hi again. I do respect the choice, but I personally don't like copying someones project and taking all the credits for it that it deserves. I believe more in the open source idea of everyone being able to work on the same project and keeping stuff central and open for everyone. I don't like the idea of everyone being able to copy someone else's work, then modifying, but never pushing it back to the original. That only pollutes the internet to my opinion.

I'm happy to publish it to npm under my username, but refer to this same github though. Would you agree on doing that? For the moment I could take care about most issues that would potentially be filed if any. I just want to keep it with the original author ;)

**Comment by chandlerprall** [comment]
👍 sent you a github collaborator invite

**Comment by ultimate-tester** [comment]
Extension published at https://www.npmjs.com/package/nunjucks-databind
